--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jaylac2000/Quests
build-by-default: true
branches:
- master
projects:
  Quests:
    path: ""
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
# - - - - 
