---
# {PLAYER} = Name of the player that finished the quest. ONLY ON REWARDS
# {QUEST} = Name of the quest. Only where they are!
# Types : move, breakblock, placeblock, kills
# Rewards are only commands !

category-select-title: "Quests"
category-select-content: "Please select a category"
quest-select-content: "Please choose a quest"
finished-quest-message: "§l§2..§e[§dQuest§e]§2..§r§f GG, you finished the quest : {QUEST}"
button-leave: "Leave"
button-info-start: "Start the quest"
button-info-pause: "Stop the quest"
quest-already-finished: "You have already finished this quest!"
paused-quest: "You stopped the quest : {QUEST}"
started-quest: "You started the quest : {QUEST}"
quest-opened: "Not started"
quest-inprogress: "§aCurrent quest"
quest-finished: "§6Completed"

categories:
  General:
    cuttree:
      name: "Example 1"
      description: "Break 5 wood"
      type: breakblock
      block: "17"
      number: 5
      rewards:
        - "give {PLAYER} dirt 64"
        - "say {PLAYER} just finished a quest"
    voyager:
      name: "Example 2"
      description: "Move 100 blocks"
      type: move
      number: 100
      rewards:
        - "give {PLAYER} steak 64"
  Others:
    example3:
      name: "Example 3"
      description: "Place 5 wood"
      type: placeblock
      block: "17"
      number: 5
      rewards:
        - "give {PLAYER} dirt 64"
    killeveryone:
      name: "Example 4"
      description: "Kill 5 players"
      type: kills
      number: 5
      rewards:
        - "give {PLAYER} diamond 1"
...