---
# {PLAYER} = Name of the player that finished the quest. ONLY WORKS ON REWARDS
# {QUEST} = Name of the quest. Only where they are!
# Types : move, breakblock, placeblock, kills

category-select-title: "Quests"
category-select-content: "Please select a category"
quest-select-content: "Please choose a quest"
finished-quest-message: "§l§2..§e[§dQuest§e]§2..§r§f GG, you finished the quest : {QUEST}"
button-leave: "Leave"
button-info-start: "Start the quest"
button-info-pause: "Stop the quest"
quest-already-finished: "§l§2..§e[§dQuest§e]§2..§r§f You have already finished this quest!"
paused-quest: "You stopped the quest : {QUEST}"
started-quest: "You started the quest : {QUEST}"
quest-opened: "Not started"
quest-inprogress: "§aCurrent quest"
quest-finished: "§6Completed"

categories:
  General: # Category Name
    cuttree: # Quest Name (config only)
      name: "Cut Tree" # Quest Name (in-game)
      description: "Get 64 Oak Wood by Breaking Trees" # Description
      type: breakblock # Type
      block: "17" # Block they need to break/place/etc
      number: 64 # Number of blocks they need to break/place/etc
      rewards: # Rewards are given by commands, you can give anything rank by a command
        - "givemoney {PLAYER} 500"
        - "say {PLAYER} just finished a quest"
    voyager: # Second Quest under General Category, you can add unlimited
      name: "Explorer"
      description: "Move 10000 blocks away from Spawn"
      type: move
      number: 10000
      rewards:
        - "give {PLAYER} steak 64"
        - "givemoney {PLAYER} 1000
  Others: # Second Category, however you can add unlimited
    Diamond:
      name: "Diamond Blocks"
      description: "Place 2 Diamond Blocks"
      type: placeblock
      block: "57"
      number: 2
      rewards:
        - "givemoney {PLAYER} 5000"
    killeveryone:
      name: "Killer"
      description: "Kill 5 players"
      type: kills
      number: 5
      rewards:
        - "give {PLAYER} diamond 3"
        - "givemoney {PLAYER} 5000
...
